version: "3.7"
services:
  app:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      NODE_ENV: development
    ports:
      - 8080:3000
    command: npm run dev

  db:
    image: mariadb:latest
    container_name: api-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: home
      MYSQL_USER: api
      MYSQL_PASSWORD: api

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: api-pma
    depends_on:
            - db
    restart: always
    environment:
      PMA_HOST: api-db
      PMA_PORT: 3306
    ports:
    - "8081:80"

volumes:
  db_data:
